# SOURCE FILENAMES
EXECUTABLE = pa2
#
# SYSTEM
CC = gcc
CFLAGS = -std=c99 -pedantic -Wvla -Wall -Wshadow -g *.c
#---------------------------------------------------------
# RULES

pa2: 
	gcc -std=c99 -pedantic -Wvla -Wall -Wshadow -g *.c -o pa2

.PHONY: pa2